export const GET_JOB_LIST = 'MY_DREAM_JOB/JOB_LIST/GET_JOB_LIST'
export const GET_JOB_LIST_SUCCESS = 'MY_DREAM_JOB/JOB_LIST/GET_JOB_LIST_SUCCESS'
export const GET_JOB_LIST_ERROR = 'MY_DREAM_JOB/JOB_LIST/GET_JOB_LIST_ERROR'
