export const GET_JOB_BY_ID = 'MY_DREAM_JOB/JOB_DETAIL/GET_JOB_BY_ID'
export const GET_JOB_BY_ID_SUCCESS = 'MY_DREAM_JOB/JOB_DETAIL/GET_JOB_BY_ID_SUCCESS'
export const GET_JOB_BY_ID_ERROR = 'MY_DREAM_JOB/JOB_DETAIL/GET_JOB_BY_ID_ERROR'
